Sprint #9
AnnaPustowit/java-filmorate pull request #1
Opened 2023-02-03 18:35 UTC by AnnaPustowit

2023-02-04 04:45 UTC, db-exp requested changes

2023-02-04 04:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 9999) {
давай в validate переместим такие вещи

2023-02-04 04:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 9999) {
или в аннотацию на уровне модели

2023-02-04 04:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() == 9999) {
по аналогии с фильмами предлагаю перенести это в валидацию или аннотацию на уровне модели

2023-02-04 13:40 UTC, AnnaPustowit commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 9999) {
исправила.

2023-02-04 13:40 UTC, AnnaPustowit commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() == 9999) {
исправила.

2023-02-05 07:59 UTC, db-exp approved these changes

2023-02-05 10:43 UTC, merged