Из develop в main
AnnaPustowit/java-filmorate pull request #11
Opened 2023-04-03 15:44 UTC by AnnaPustowit

2023-04-04 12:36 UTC, db-exp requested changes

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        Director director1 = directorService.create(director);
лучше не называть имя переменной 1,2,3 - лучше назвать входной directorInput или directorRequest итп

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director getDirectorById(@PathVariable int id) {
можно добавить валидацию на id, что оно не должно быть меньше нуля (Min=1)

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director update(@RequestBody Director director) {
тоже, что и в первом методе про director1

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          if (film.getReleaseDate() == null || film.getReleaseDate().isBefore(DATE)) {
чтобы не привязываться к дате тут можно сделать кастомную валидацию и повесить аннотацию на модель 
https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (sortBy.equals("year")) {
в контроллере нет проверки на пустоту и будет npe если не передадут, лучше если параметр пустой ставить по умолчанию значение, например, по годам или по лайкам как тут
Дополнительно можно вариант сортировки в enum обернуть

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private int id;
лучше сразу привыкать к long для id (еще uuid любят использовать), int можно в данном проекте

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +        Map<String, Object> values = new HashMap<>();
Map<String, Object> - не совсем корректно, лучше чуть более конкретно -  Map<String, String>

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (by.contains("title") && by.contains("director")) {
by может быть null лучше сделать дефолтное значение

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void del(int id);
лучше delete

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getDirectorById(int directorId);
лучше во всех storage называть однообразно findById

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Integer result1 = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM popular_films " +
лучше вместо result1 - likesCount

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Director director = directorStorage.getDirectorById(directorId);
можно так, но лучше доставать Optional и через orElseThrow кидать ошибку

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film1 : films) {
нейминг - лучше tmpFilm или просто film или еще вариант через films.forEach( film -> {} )

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "LEFT JOIN ratings mpa ON f.rating_id = mpa.rating_id " +
в запросах лучше придерживаться одного стиля написания - если имена таблиц с большой, то везде

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Director director = directorStorage.getDirectorById(directorId);
как в методе выше - можно Optional

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film1 : films) {
нейминг

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql1 = "SELECT *,df.film_id " +
давай объединим запросы  с режиссерами через join

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.query("SELECT *,df.film_id " +
и тут тоже лучше объединить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql1 = "SELECT *,df.film_id " +
и тут лучше объединить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.update("DELETE FROM films WHERE film_id = ?", filmId);
тогда нужно и связку с режиссером разрывать, чтобы данные были консистентными, а то получится, что режиссер соотносится с фильмом, которого уже нет

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            String sql2 = "SELECT *,df.film_id " +
выше уже объединенный запрос - можно из его результатов собирать ответ

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            String sql2 = "SELECT *,df.film_id " +
а тут лучше объединить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql2 = "SELECT *,df.film_id " +
и тут

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.update("DELETE DIRECTORS_FILMS WHERE film_id=?", film.getId());
лучше сначала проверить на пустоту, а потом отправлять запрос

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> assignDirectors(ResultSet rs, List<Film> films, Map<Integer, Set<Director>> filmsDirectors) throws SQLException;
наружу SQLException прокидывать не очень правильно, если нужно - лучше кастомную ошибку

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql1 = "SELECT film_id FROM popular_films " +
тут и ниже вместо sql1,2 лучше писать понятные имена.
Например selectUserFilms
Второй момент - лучше этот запрос отправить в FilmStorage getPopularFilmsByUserIds(), который вернет, например, список фильмов

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql = "SELECT f.*, mpa.name_rating " +
запрос лучше отправить в FilmStorage - getPopularFilmsByUserIds(), а потом тут отфильтровать userFilms

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql3 = "SELECT *,df.film_id " +
это точно должно быть в filmStorage - я оставил комментарий там, что лучше получать сразу с режиссерами

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        return jdbcTemplate.query("SELECT * " +
такой вызов должен быть в FeedStorage

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public void saveFeed(Integer userId, EventType ev, Operation op, Integer entityId) {
тоже нужно вынести в отдельный FeedStorage

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        jdbcTemplate.update("DELETE FROM users WHERE user_id = ?", userId);
дружба/ленты/лайки итд тоже должны быть изменены
Либо нужно добавлять для пользователя признак DELETED и учитывать в других запросах

Обычно в похожих системах две стратегии - либо все подчистить, либо, если это сложно - везде начинать учитывать помеченные как удаленные данные

2023-04-04 12:36 UTC, db-exp commented on src/main/resources/schema.sql
> +    user_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
у  user и film id - integer, либо там тоже надо long(bigint), либо тут int

2023-04-04 12:36 UTC, db-exp commented on src/main/resources/schema.sql
> +    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
integer

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addLike(@PathVariable("id") int id, @PathVariable("userId") int userId) {
для userId тоже можно валидацию поставить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addDislike(@PathVariable("id") int id, @PathVariable("userId") int userId) {
для параметров тоже можно валидацию поставить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void del(@PathVariable("id") int id) {
тоже можно валидацию поставить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void delLike(@PathVariable("id") int id, @PathVariable("userId") int userId) {
для параметров тоже можно валидацию поставить

2023-04-04 12:36 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void delDislike(@PathVariable("id") int id, @PathVariable("userId") int userId) {
для параметров тоже можно валидацию поставить

2023-04-04 12:53 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        Director director1 = directorService.create(director);
Окей.Исправил

2023-04-04 12:54 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director update(@RequestBody Director director) {
Исправил

2023-04-04 13:06 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director getDirectorById(@PathVariable int id) {
Окей.Исправил

2023-04-04 13:39 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (sortBy.equals("year")) {
Окей.Добавил значение по умолчанию likes.

2023-04-04 13:48 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +        Map<String, Object> values = new HashMap<>();
Да согласен.Изменил

2023-04-04 13:57 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (by.contains("title") && by.contains("director")) {
Исправил, дефолтное значение "title"

2023-04-04 14:02 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getDirectorById(int directorId);
Окей.Изменил все.

2023-04-04 14:07 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Integer result1 = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM popular_films " +
Окей.Исправил

2023-04-04 14:17 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Director director = directorStorage.getDirectorById(directorId);
Тут убрал проверку так как она уже есть в хранилище и там через orElseThrow кидаю ошибку.

2023-04-04 14:23 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film1 : films) {
Окей.Использовал вариант films.forEach( film -> {} )

2023-04-04 14:26 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "LEFT JOIN ratings mpa ON f.rating_id = mpa.rating_id " +
Исправил.В моем проекте с большой буквы поэтому тут автоматом написал тоже с большой.

2023-04-04 14:37 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        Director director = directorStorage.getDirectorById(directorId);
Исправил

2023-04-04 14:37 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film1 : films) {
Исправил

2023-04-04 14:49 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql1 = "SELECT *,df.film_id " +
Первый запрос был написан до группового проекта.В моем проекте он совершенно другой.Наличие двух запросов допустимо этот вопрос обсуждался с моим ревьюером и наставником.Оставлю как есть в данном ГП.

2023-04-04 14:51 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql1 = "SELECT *,df.film_id " +
Оставляю

2023-04-04 14:52 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.query("SELECT *,df.film_id " +
Оставляю

2023-04-04 15:08 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            String sql2 = "SELECT *,df.film_id " +
Запрос выше не заполняет поле режиссёра, потому что используется маппер из старого кода. Новым запросом просто добавляю режиссёра. Обсуждал со своим ревьюером.

2023-04-04 15:11 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            String sql2 = "SELECT *,df.film_id " +
как и в предыдущем с добавлением режиссёров.

2023-04-04 15:14 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.update("DELETE DIRECTORS_FILMS WHERE film_id=?", film.getId());
Исправил

2023-04-04 15:18 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.update("DELETE FROM films WHERE film_id = ?", filmId);
Удаление происходит каскадное.
CREATE TABLE if not exists directors_films (
    director_id int not null references directors(director_id) ON DELETE CASCADE,
    film_id  int not null references films(film_id) ON DELETE CASCADE,

    PRIMARY KEY(director_id,film_id)
);

2023-04-04 15:32 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        jdbcTemplate.update("DELETE FROM users WHERE user_id = ?", userId);
Везде стоит каскадное удаление.Признак DELETED не нужен так как нет необходимости восстанавливать эти данные.Значит мы используем первую стратегию и все чистим.Не понимаю данного замечания.

2023-04-04 16:09 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        return jdbcTemplate.query("SELECT * " +
Окей.Создал FeedStorage.

2023-04-04 16:09 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public void saveFeed(Integer userId, EventType ev, Operation op, Integer entityId) {
Окей.Создал FeedStorage.

2023-04-04 17:28 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        jdbcTemplate.update("DELETE DIRECTORS_FILMS WHERE film_id=?", film.getId());
Если проверить сначала на пустоту то ложатся 2 теста постмана.Надо удалить в любом случае хоть пусто хоть нет.

2023-04-04 17:28 UTC, AleksandrBondar24 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> assignDirectors(ResultSet rs, List<Film> films, Map<Integer, Set<Director>> filmsDirectors) throws SQLException;
Исправил

2023-04-04 20:06 UTC, AnnaPustowit commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql1 = "SELECT film_id FROM popular_films " +
исправила названия локальных переменных

2023-04-04 20:07 UTC, AnnaPustowit commented on src/main/resources/schema.sql
> +    user_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
теперь через int

2023-04-05 04:34 UTC, db-exp requested changes

2023-04-05 04:34 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/annotation/filmDate/FilmDateValidator.java
> +public class FilmDateValidator implements ConstraintValidator<ValidDate, LocalDate> {
отформатируйте, пожалуйста, код
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2023-04-05 04:34 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/annotation/validLogin/UserLoginValidator.java
> +public class UserLoginValidator implements ConstraintValidator<ValidLogin, String> {
отформатируйте, пожалуйста, код
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2023-04-05 04:34 UTC, db-exp commented on src/main/resources/schema.sql
> +    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
тут user_id так и остался bigint

2023-04-05 04:34 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        jdbcTemplate.update("DELETE FROM users WHERE user_id = ?", userId);
Ок, если все чистить - тогда хорошо

2023-04-05 04:34 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public List<Film> getRecommendation(int id) {
Давайте все таки перенесем в FilmStorage - некорректно UserStorage возвращать список фильмов
Получается смешение ответственности

2023-04-05 06:12 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public List<Film> getRecommendation(int id) {
исправили

2023-04-05 06:13 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/annotation/validLogin/UserLoginValidator.java
> +public class UserLoginValidator implements ConstraintValidator<ValidLogin, String> {
сделано

2023-04-05 06:14 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/annotation/filmDate/FilmDateValidator.java
> +public class FilmDateValidator implements ConstraintValidator<ValidDate, LocalDate> {
сделано

2023-04-05 07:59 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage, FeedStorage feedStorage, FilmStorage filmStorage) {
более правильно использовать сервисы - FilmService, FeedService

2023-04-05 08:01 UTC, db-exp approved these changes

2023-04-05 09:50 UTC, SergeySviridov36 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage, FeedStorage feedStorage, FilmStorage filmStorage) {
Вынесли метод getRecomendation в FilmService, внедрение feedStorage в UserService оставляем

2023-04-05 13:17 UTC, BonibrNastya approved these changes

2023-04-05 13:18 UTC, merged